In [ ]:
# Import TensorFlow into Colab
import tensorflow as tf
import tensorflow_hub as hub
print("TensorFlow Version : ", tf.__version__)
print("TensorFlow Hub Version : ", hub.__version__)

TensorFlow Version :  2.12.0
TensorFlow Hub Version :  0.13.0


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# !unzip "/content/drive/MyDrive/SkinDiseaseClassifier.zip" -d "/content/drive/MyDrive/SkinDiseaseClassifier"

In [ ]:
import warnings
warnings.simplefilter("ignore", category=PendingDeprecationWarning) # Handle Deprecation Warnings

In [ ]:
import pandas as pd
labels = pd.DataFrame(columns = ["filenames","labels"])
labels

Empty DataFrame
Columns: [filenames, labels]
Index: []

In [ ]:
import os
i = "/content/drive/MyDrive/SkinDiseaseClassifier/train/"
for j in os.listdir(i):
    for k in os.listdir(i+j+"/"):
        labels.loc[len(labels.index)] = [i+j+"/"+k, j]

labels.to_csv("/content/drive/MyDrive/SkinDiseaseClassifier/labels.csv")

In [ ]:
# # Import CSV
# import os
# import pandas as pd
# import numpy as np
# labels = pd.read_csv('/content/drive/MyDrive/SkinDiseaseClassifier/labels.csv')
# unique_labels = np.unique(labels["labels"])

In [ ]:
labels.tail()

filenames  \
1899  /content/drive/MyDrive/SkinDiseaseClassifier/t...   
1900  /content/drive/MyDrive/SkinDiseaseClassifier/t...   
1901  /content/drive/MyDrive/SkinDiseaseClassifier/t...   
1902  /content/drive/MyDrive/SkinDiseaseClassifier/t...   
1903  /content/drive/MyDrive/SkinDiseaseClassifier/t...   

                                                 labels  
1899  Tinea Ringworm Candidiasis and other Fungal In...  
1900  Tinea Ringworm Candidiasis and other Fungal In...  
1901  Tinea Ringworm Candidiasis and other Fungal In...  
1902  Tinea Ringworm Candidiasis and other Fungal In...  
1903  Tinea Ringworm Candidiasis and other Fungal In...

In [ ]:
# Create pathnames from image IDs
filenames = []
for i in range(0, len(labels)):
    filenames.append(labels["filenames"][i])

# Check the first 10
filenames[:10]

['/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-6.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-129.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-closed-comedo-4.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-92.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/07AcnePittedScars1.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-16.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-87.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-29.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-cystic-39.jpg',
 '/content/drive/MyDrive/SkinDiseaseClassifier/train/Acne and Rosacea Photos/acne-closed-comedo-19.jpg']

In [ ]:
labels = labels["labels"]
labels.head()

0    Acne and Rosacea Photos
1    Acne and Rosacea Photos
2    Acne and Rosacea Photos
3    Acne and Rosacea Photos
4    Acne and Rosacea Photos
Name: labels, dtype: object

## Import CSV & Make Labels

In [ ]:
import numpy as np
import pandas as pd
# Check if all labels are unique
labels = pd.read_csv('/content/drive/MyDrive/SkinDiseaseClassifier/labels.csv')
unique_labels = np.unique(labels["labels"])
len(unique_labels)

4

In [ ]:
# Turn every label into a boolean array (Compare with all breeds and the only True value will be the class it belongs to)
labels = labels["labels"]
print(labels)
labels[0] == unique_labels

0                                 Acne and Rosacea Photos
1                                 Acne and Rosacea Photos
2                                 Acne and Rosacea Photos
3                                 Acne and Rosacea Photos
4                                 Acne and Rosacea Photos
                              ...                        
1899    Tinea Ringworm Candidiasis and other Fungal In...
1900    Tinea Ringworm Candidiasis and other Fungal In...
1901    Tinea Ringworm Candidiasis and other Fungal In...
1902    Tinea Ringworm Candidiasis and other Fungal In...
1903    Tinea Ringworm Candidiasis and other Fungal In...
Name: labels, Length: 1904, dtype: object


array([ True, False, False, False])

In [ ]:
# Do this for all labels

boolean_labels = [label == unique_labels for label in labels]
boolean_labels[:2]

[array([ True, False, False, False]), array([ True, False, False, False])]

In [ ]:
len(boolean_labels)

1904

In [ ]:
# Setup X and y variables

X = filenames
y = boolean_labels

In [ ]:
len(filenames)

1904

In [ ]:
# Let's split our data using Scikit-Learn's train-test-split
from sklearn.model_selection import train_test_split

# Split into training & validation sets
X_train, X_val, y_train, y_val = train_test_split(X,
                                                  y,
                                                  test_size = 0.2,
                                                  random_state = 42)

len(X_train), len(y_train), len(X_val), len(y_val)

(1523, 1523, 381, 381)

In [ ]:
# Let's have a gaze at the training data (filenames & boolean_labels)
X_train[0], y_train[0]

('/content/drive/MyDrive/SkinDiseaseClassifier/train/Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions/granulation-tissue-25.jpg',
 array([False,  True, False, False]))

In [ ]:
# Convert image to NumPy array
from matplotlib.pyplot import imread
image = imread(filenames[42])
image.shape # Height, Width, Colour Channel (RGB)

(720, 478, 3)

In [ ]:
image.max(), image.min() # All values are pixel brightness values between 0 and 255

(255, 0)

In [ ]:
image[:2]

array([[[112,  73,  78],
        [111,  72,  77],
        [111,  72,  77],
        ...,
        [100,  75,  79],
        [100,  75,  79],
        [100,  75,  79]],

       [[115,  76,  81],
        [114,  75,  80],
        [113,  74,  79],
        ...,
        [ 98,  73,  77],
        [ 99,  74,  78],
        [ 99,  74,  78]]], dtype=uint8)

## Processing Function

In [ ]:
# Define image size
IMG_SIZE = 480

# Create a function for preprocessing images
def process_image(image_path):
  """
  Takes an image file path and turns the image into a Tensor
  """
  # Read in an image file
  image = tf.io.read_file(image_path)

  # Turn the jpg image into a numerical tensor with three color channels (RGB)
  image = tf.image.decode_jpeg(image, channels = 3)

  # Convert the colour channel values from 0-255 values to 0-1 values (Image Representation Using Floating Points Needs 0-1 Values)
  image = tf.image.convert_image_dtype(image, tf.float32) # Normalization !

  # Resize our image to our desired size (224,224)
  image = tf.image.resize(image, size = [IMG_SIZE, IMG_SIZE])

  return image

## Processing Function

In [ ]:
# Create a simple function to return a tuple (image, label)
def get_image_label(image_path, label):
  """
  Takes an image file path and the associated label
  Processes image and returns tuple of (image, label)
  """
  image = process_image(image_path)
  return image, label

## Processing Function

In [ ]:
# Define the batch size, 16 is a good start
BATCH_SIZE = 16

# Create a function to turn our data into batches
def create_data_batches(X, y = None, batch_size = BATCH_SIZE, val_data = False, test_data = False):
  """
  Creates batches of data out of image (X) and label (y) pairs.
  Shuffles the data if it's training data but doesn't shuffle if it's validation data.
  Also accepts test data as input (No Labels)
  """
  # If the data is a test dataset, we don't have labels
  if test_data:
    print("Creating test data batches...")
    data = tf.data.Dataset.from_tensor_slices((tf.constant(X))) # Only filepaths, no labels (Makes dataset from slices of given tensor)
    data_batch = data.map(process_image).batch(BATCH_SIZE) # Creates batches of given batch size
    return data_batch

  # If the data is validation dataset, we don't need to shuffle it
  elif val_data:
    print("Creating validation data batches...")
    data = tf.data.Dataset.from_tensor_slices((tf.constant(X),  # filepaths
                                               tf.constant(y))) # labels
    data_batch = data.map(get_image_label).batch(BATCH_SIZE)
    return data_batch

  else: # It's training data
    print("Creating training data batches...")
    # Turn filepaths and labels into tensors
    data = tf.data.Dataset.from_tensor_slices((tf.constant(X),
                                               tf.constant(y)))
    # Shuffling before preprocessing images is faster
    data = data.shuffle(buffer_size = len(X))

    # Create (image, label) tuples and preprocess the image
    data_batch = data.map(get_image_label).batch(BATCH_SIZE)
    return data_batch

In [ ]:
# Creating training and validation data batches

train_data = create_data_batches(X_train, y_train)
val_data = create_data_batches(X_val, y_val, val_data = True)

Creating training data batches...
Creating validation data batches...


In [ ]:
# Setup input shape
INPUT_SHAPE = [None, IMG_SIZE, IMG_SIZE, 3] # (batch size, height, width, color channels)

# Setup output shape
OUTPUT_SHAPE = len(unique_labels)

# Setup model URL
MODEL_URL = "https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet21k_ft1k_m/feature_vector/2"

In [ ]:
from tensorflow import keras # Importing Keras API
from keras.models import Sequential # Importing The Sequential Model From Keras API
from keras.layers import Dense # Importing The Dense Layer From Keras API
from keras.losses import CategoricalCrossentropy
from keras.optimizers import Adam

# Create a function which builds a Keras model

def create_model(input_shape = INPUT_SHAPE, output_shape = OUTPUT_SHAPE, model_url = MODEL_URL):
  print("Building Model With : ", model_url)
  feature_extractor = hub.KerasLayer(model_url, trainable = True)

  # Setting Up The Model Layers
  model = Sequential([
      feature_extractor, # Layer 1 - Input Layer
      Dense(256, activation='relu'),
      Dense(units = OUTPUT_SHAPE,
            activation = "linear") # Layer 2 - Output Layer (Softmax Classification)
  ])

  # Compile The Model
  model.compile(
      loss = CategoricalCrossentropy(),
      optimizer = Adam(),
      metrics = ["accuracy"]
  )

  # Build The Model
  model.build(input_shape)

  return model

In [ ]:
model = create_model()
model.summary()

Building Model With :  https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet21k_ft1k_m/feature_vector/2
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 1280)              53150388  
                                                                 
 dense (Dense)               (None, 256)               327936    
                                                                 
 dense_1 (Dense)             (None, 4)                 1028      
                                                                 
Total params: 53,479,352
Trainable params: 53,187,320
Non-trainable params: 292,032
_________________________________________________________________


In [ ]:
# Load TensorBoard Notebook Extension

%load_ext tensorboard
# Magic Function To Load Notebook Extension

In [ ]:
import datetime
from keras.callbacks import TensorBoard, EarlyStopping
# Create a function to build a TensorBoard Callback

def create_tensorboard_callback():

  # Create a log directory to store TensorBoard logs which get tracked whenever we run an experiment
  logdir = os.path.join("drive/MyDrive/SkinDiseaseClassifier/logs",
                        datetime.datetime.now().strftime("%Y%m%d-%H%m%s"))
  return TensorBoard(logdir)

In [ ]:
# Create Early Stopping Callback ( Monitor - Value To Be Tracked For Stopping , Patience = No. Of Epochs To Tolerate)

early_stopping = EarlyStopping(monitor = "val_accuracy",
                               patience = 3)

In [ ]:
# Build a function to train and return a model
def train_model():
  """
  Trains a given model and returns the trained version.
  """
  # Create a model
  model = create_model()

  # Create new TensorBoard session whenever we train our model
  tensorboard = create_tensorboard_callback()

  # Fit the model to the data passing it the callbacks we created
  model.fit(x = train_data,
            epochs = 100,
            validation_data = val_data,
            validation_freq = 1,
            callbacks = [tensorboard, early_stopping])

  # Return the fitted model
  return model

In [ ]:
#  Fit the model to our data
model = train_model()

Building Model With :  https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet21k_ft1k_m/feature_vector/2
Epoch 1/100


ResourceExhaustedError: ignored